### ISSUE TITLE
How to handle configuration, not services?

### ISSUE THREAD

**Issue by Koc** [opensky/OpenSkyRuntimeConfigBundle#6]
Hello!

There is part from configuration

``` yaml
services:
    runtime_parameters.security.firewalls.main.remember_me.domain:
        public: false
        class: stdClass
        factory_service: opensky.runtime_config
        factory_method: get
        arguments:
            - security.firewalls.main.remember_me.domain

security:
    firewalls:
        main:
            pattern: .*
            remember_me:
                # ...
                domain: @runtime_parameters.security.firewalls.main.remember_me.domain
```

It doesnt works as expected:

``` php
        $g = new \Symfony\Component\Security\Http\RememberMe\TokenBasedRememberMeServices(array(0 => $b), 'fe1qwd3', 'main', array('name' => 'remember_me', 'lifetime' => '8640000', 'path' => '/',

// as you see - it just use string but not calling service
'domain' => '@runtime_parameters.security.firewalls.main.remember_me.domain',

'secure' => false, 'httponly' => true, 'always_remember_me' => true, 'remember_me_parameter' => '_remember_me'), $c);
```

What you can advice for me?
